version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests
          command: yarn test
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
                # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
      	        # taken to be the root directory of the workspace.
                root: ~/repo
                # Must be relative path from root
                paths:
                  - dist
  deploy:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/repo/dist
      - run:
          name: Prepare Git
          command: |
            cd dist &&
            git init
      - run:
          name: Deploy to Heroku
          command: |
            cd dist &&
            git add . &&
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
